### ISSUE TITLE
IceCap missing dependency?

### ISSUE THREAD

**Issue by michaelBenin** [nanopx/gulp-esdoc#10]
var logger = new Logger("IceCap");
             ^

TypeError: Logger is not a function

**Comment by arcticShadow** [comment]
I'm experiencing this too. 

'Logger' is actually an instance of 'color-logger' and as far as i can tell it is actually there.

**Comment by arcticShadow** [comment]
also - ice-cap and color-logger and made by the same author as esdoc, and are not dependencies of this project, but of esdoc

**Comment by arcticShadow** [comment]
This has been fixed in esdoc - even though there is no mention of it. (ESDoc has bumped dependency on ice-cap to 0.0.4, where the issue is resolved) so in theory this module need sto bump to esdoc 0.4.7

**Comment by nanopx** [comment]
Closing this for now, should be solved #13
